name: Deploy Probot App

on: 
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                node-version: '21.6.0'

            - name: Use Node.js
              uses: actions/setup-node@v4

            - name: Install dependencies
              run: npm install

            - name: Start
              run: npm start